version: "3.5"

services:
  webapi01: &webapi
    image: pedroter7/rinha-de-backend-2024-q1:webapi-latest
    hostname: webapi01
    environment:
      - CUSTOMCONNSTR_MariaDbRead=Server=db;User Id=root;Password=pwd;Database=rinha_2024_q1
      - CUSTOMCONNSTR_MariaDbWrite=Server=db;User Id=root;Password=pwd;Database=rinha_2024_q1
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  webapi02:
    <<: *webapi
    hostname: webapi02
    environment:
      - CUSTOMCONNSTR_MariaDbRead=Server=db;User Id=root;Password=pwd;Database=rinha_2024_q1
      - CUSTOMCONNSTR_MariaDbWrite=Server=db;User Id=root;Password=pwd;Database=rinha_2024_q1

  loadbalancer:
    image: pedroter7/rinha-de-backend-2024-q1:loadbalancer-latest
    depends_on:
      - webapi01
      - webapi02
    ports:
      - "9999:80"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: pedroter7/rinha-de-backend-2024-q1:db-latest
    hostname: db
    environment:
      - MARIADB_ROOT_PASSWORD=pwd
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: rinha-2024-q1
